version: "3.8"

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment: 
      - POSTGRES_HOST=db
    depends_on: 
      - db

  db:
    image: postgres:14-alpine
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data/
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=baania
    
volumes: 
  postgres_data: